from csv import reader
import os

caseTypeChoices = [
    ("Health", "Health"),
    ("Education", "Education"),
    ("Food Assistance", "Food Assistance"),
    ("Cash Assistance", "Cash Assistance"),
    ("Legal Support", "Legal Support"),
    ("NFI Support", "NFI Support"),
    ("Protection From Violence", "Protection From Violence"),
    ("MHPSS", "MHPSS"),
    ("Child Protection", "Child Protection"),
    ("Detention/Deportation", "Detention/Deportation"),
    ("Other", "Other")
]

psnTypeChoices = [
    ("Pregnant", "Pregnant"),
    ("Elderly", "Elderly"),
    ("Unaccompanied And/Or Seperated Children", "Unaccompanied And/Or Seperated Children"),
    ("Chronic Disease", "Chronic Disease"),
    ("Disability", "Disability"),
]

caseStatusChoices = [
    ("REQUEST RECEIVED", "Request Received"),
    ("REQUEST VIEWED", "Request Viewed"),
    ("REQUEST REFERRED", "Request Referred"),
    ("CASE WORKER ASSIGNED", "Case Worker Assigned"),
    ("FIRST CONTACT SCHEDULED", "First Contact Scheduled"),
    ("CASE CLOSED", "Case Closed")
]

caseCoverageChoices = [
    ("INDIVIDUAL", "Individual"),
    ("HOUSEHOLD", "Household")
]

userGenderChoices = [
    ("MALE", "Male"),
    ("FEMALE", "Female"),
    ("NON BINARY", "Non Binary"),
    ("OTHER", "Other")
]

vulnerabilityCategoryChoices = [
    ("LOW RISK", "Low Risk"),
    ("MODERATE RISK", "Moderate Risk"),
    ("HIGH RISK", "High Risk"),
]

caseFeedbackRatingChoices = [
    (1, 'One'),
    (2, 'Two'),
    (3, 'Three'),
    (4, 'Four'),
    (5, 'Five'),
]

userCountryOfAsylumChoices = [
    ("Afghanistan", "افغانستانAfghanestan"),
    ("Albania", "Shqipëria"),
    ("Algeria", "Dzayer"),
    ("Andorra", "Andorra"),
    ("Angola", "Angola"),
    ("Antigua and Barbuda", "Antigua and Barbuda"),
    ("Argentina", "Argentina"),
    ("Armenia", "Hayastán"),
    ("Australia", "Australia"),
    ("Austria", "Österreich"),
    ("Azerbaijan", "Azərbaycan"),
    ("The Bahamas", "The Bahamas"),
    ("Bahrain", "البحرينAl-Bahrayn"),
    ("Bangladesh", "Bangladesh বাংলাদেশ"),
    ("Barbados", "Barbados"),
    ("Belarus", "Bielaruś, Беларусь"),
    ("Belgium", "België, Belgique, Belgien"),
    ("Belize", "Belize"),
    ("Benin", "Bénin"),
    ("Bhutan", "Druk Yul, འབྲུག་ཡུལ"),
    ("Bolivia", "Wuliwya, Volívia, Buliwya, Bolivia"),
    ("Bosnia and Herzegovina", "Bosnia I Hercegovína, Босна и Херцеговина"),
    ("Botswana", "Botswana"),
    ("Brazil", "Brasil"),
    ("Brunei", "Brunei بروني"),
    ("Bulgaria", "Bulgariya, България"),
    ("Burkina Faso", "Burkina Faso"),
    ("Burundi", "Burundi, Uburundi"),
    ("Cambodia", "Kampuchea កម្ពុជា"),
    ("Cameroon", "Cameroon, Cameroun"),
    ("Canada", "Canada"),
    ("Cape Verde", "Cabo Verde"),
    ("Central African Republic", "République Centrafricaine, Ködörösêse tî Bêafrîka"),
    ("Chad", "Tchad, تشاد"),
    ("Chile", "Chile"),
    ("China", "Zhōngguó 中国"),
    ("Colombia", "Colombia"),
    ("Comoros", "جزر القمر Comores Koromi"),
    ("Republic of the Congo", "République du Congo, Republíki ya Kongó"),
    ("Democratic Republic of the Congo", "République démocratique du Congo, Republíki ya Kongó, Demokratíki Jamhuri ya Kidemokrasia ya Kongo"),
    ("Costa Rica", "Costa Rica"),
    ("Côte d'Ivoire", "Côte d'Ivoire"),
    ("Croatia", "Hrvatska"),
    ("Cuba", "Cuba"),
    ("Cyprus", "Κύπρος Kıbrıs"),
    ("Czechia", "Česko"),
    ("Denmark", "Danmark"),
    ("Djibuti", "جيبوتي Djibouti"),
    ("Dominica Republic", "República Dominicana"),
    ("East Timor", "Timor-Lester, Timor Lorosa'e"),
    ("Ecuador", "Ecuador"),
    ("Egypt", "مصرMisr"),
    ("El Salvador", "El Salvador"),
    ("Equatorial Guinea", "Guinea Ecuatorial"),
    ("Eritrea", "Iritriya إرتريا Ertra"),
    ("Estonia", "Eesti"),
    ("Eswatini", "Eswatini, eSwatini"),
    ("Ethiopia", "Ityop'ia ኢትዮጵያ"),
    ("Fiji", "Fiji, Viti, फ़िजी"),
    ("Finland", "Suomi, Finland"),
    ("France", "France"),
    ("Gabon", "République gabonaise"),
    ("The Gambia", "The Gambia"),
    ("Georgia", "Sak'art'velo საქართველო"),
    ("Germany", "Deutschland"),
    ("Ghana", "Gaana, Ghana, Gana, Gana"),
    ("Greece", "Hellas Ελλάς"),
    ("Grenada", "Grenada"),
    ("Guatemala", "Guatemala"),
    ("Guinea", "Guinée, Gine, Gine"),
    ("Guyana", "Guyana"),
    ("Haiti", "Haïti, Ayiti"),
    ("Honduras", "Honduras"),
    ("Hong Kong", "Hong Kong, Heung Gong, 香港"),
    ("Hungary", "Magyarország"),
    ("Iceland", "Ísland"),
    ("India", "Bharôt ভাৰত, Bharôt ভারত, India, Bhārat ભારત, Bhārat भारत, Bhārata ಭಾರತ, Bhārat भारत, Bhāratam ഭാരതം, Bhārat भारत, Bhārat भारत, Bharôtô ଭାରତ, Bhārat ਭਾਰਤ, Bhāratam भारतम्, Bārata பாரதம், Bhāratadēsam భారత దేశం"),
    ("Indonesia", "Indonesia"),
    ("Iran", "Īrān ایران"),
    ("Iraq", "Al-'Iraq العراق"),
    ("Ireland", "Ireland, Éire"),
    ("Israel", "Israʼiyl إسرائيل, Yisra'el ישראל"),
    ("Italy", "Italia"),
    ("Jamaica", "Jamaica"),
    ("Japan", "Nippon 日本"),
    ("Jordan", "Al-'Urdun الأردن"),
    ("Kazakhstan", "Qazaqstan Қазақстан, Kazakhstán Казахстан"),
    ("Kenya", "Kenya"),
    ("North Korea", "Chosŏn 조선 Bukchosŏn 북조선"),
    ("South Korea", "Hanguk 한국 Namhan 남한"),
    ("Kosovo", "Kosova, Косово"),
    ("Kuwait", "Dawlat ul-Kuwayt دولة الكويت"),
    ("Kyrgyzstan", "Kyrgyzstan Кыргызстан, Kirgizija Киргизия"),
    ("Laos", "Lao ປະເທດລາວ"),
    ("Latvia", "Latvija"),
    ("Lebanon", "Lubnān لبنان, Liban"),
    ("Lesotho", "Lesotho"),
    ("Libya", "Libya, Lībiyā ليبيا"),
    ("Liechtenstein", "Liechtenstein"),
    ("Lithuania", "Lietuva"),
    ("Luxembourg", "Luxembourg, Luxemburg, Lëtezebuerg"),
    ("Madagascar", "Madagascar, Madagasikara"),
    ("Malawi", "Malaŵi, Malawi"),
    ("Malaysia", "Mǎláixīyà 马来西亚, Malaysia, மலேசியா"),
    ("Maldives", "Dhivehi Raajje"),
    ("Mali", "Mali, Mali"),
    ("Malta", "Malta, Malta"),
    ("Marshall Islands", "Marshall Islands, Aorōkin M̧ajeļ"),
    ("Mauritania", "Muritan / Agawec, Mūrītānyā موريتانيا"),
    ("Mauritius", "Mauritius, Maurice, Moris"),
    ("Mexico", "Mēxihco, México"),
    ("Federated States of Micronesia", "Federated States of Micronesia"),
    ("Moldova", "Moldova"),
    ("Monaco", "Monaca, Múnegu"),
    ("Mongolia", "Mongol Uls Монгол Улс"),
    ("Montenegro", "Crna Gora Црна Гора"),
    ("Morocco", "Al-maɣréb المغرب, Amerruk / Elmeɣrib"),
    ("Mozambique", "Moçambique"),
    ("Myanmar", "Myanma မြန်မာ"),
    ("Namibia", "Namibia, Namibia, Namibia, Namibia, Namibia"),
    ("Nepal", "Nepāl नेपाल"),
    ("The Netherlands", "Nederland, Nederlân"),
    ("New Zealand", "New Zealand, Aotearoa"),
    ("Nicaragua", "Nicaragua"),
    ("Niger", "Niger"),
    ("Nigeria", "Nigeria, Nijeriya, Naigeria, Nàìjíríà"),
    ("North Macedonia", "Severna Makedonija Северна Македонија"),
    ("Norway", "Norge"),
    ("Oman", "‘Umān عُمان"),
    ("Pakistan", "Pākistān پاکستان"),
    ("Palau", "Palau, Belau"),
    ("Palestine", "Filasṭīn فلسطين"),
    ("Panama", "Panamá"),
    ("Papua New Guinea", "Papua New Guinea, Papua Niugini, Papua Giugini"),
    ("Paraguay", "Paraguái, Paraguay"),
    ("Peru", "Piruw, Perú"),
    ("Philippines", "Philippines, Pilipinas"),
    ("Poland", "Polska"),
    ("Portugual", "Portugal"),
    ("Qatar", "Qaṭar قطر"),
    ("Romania", "România"),
    ("Russia", "Rossiâ Россия"),
    ("Rwanda", "Rwanda"),
    ("Saint Kitts and Nevis", "Saint Kitts and Nevis"),
    ("Saint Lucia", "Saint Lucia"),
    ("Saint Vincent and the Grenadines", "Saint Vincent and the Grenadines"),
    ("Samoa", "Samoa, Sāmoa"),
    ("San Marino", "San Marino"),
    ("São Tomé and Principe", "São Tomé e Principe"),
    ("Saudi Arabia", "Al-‘Arabiyyah as Sa‘ūdiyyah المملكة العربية السعودية"),
    ("Senegal", "Sénégal"),
    ("Serbia", "Srbija Србија"),
    ("Seychelles", "Seychelles, Seychelles, Sesel"),
    ("Sierra Leone", "Sierra Leone"),
    ("Singapore", "Singapore, Singapura, 新加坡, சிங்கப்பூர்"),
    ("Slovakia", "Slovensko"),
    ("Slovenia", "Slovenija"),
    ("Solomon Islands", "Solomon Islands, Solomon Aelan"),
    ("Somalia", "Soomaaliya aş-Şūmāl, الصومال"),
    ("South Africa", "Suid-Afrika, South Africa, iNingizimu Afrika, uMzantsi Afrika, Afrika-Borwa, Afrika Borwa, Aforika Borwa, Afurika Tshipembe, Afrika Dzonga, iNingizimu Afrika, iSewula Afrika"),
    ("South Sudan", "South Sudan, Paguot Thudän, Sudan Kusini"),
    ("Spain", "España, Espanya, Espainia"),
    ("Sri Lanka", "Sri Lankā ශ්‍රී ලංකාව இலங்கை"),
    ("Sudan", "As-Sudan السودان"),
    ("Sweden", "Sverige"),
    ("Switzerland", "Suisse, Schweiz, Svizzera, Svizra"),
    ("Syria", "Suriyah سورية"),
    ("Tajikistan", "Tojikistan Тоҷикистон"),
    ("Tanzania", "Tanzania"),
    ("Thailand", "Mueang Thai, Prathet Thai, Ratcha-anachak Thai เมืองไทย, ประเทศไทย, ราชอาณาจักรไทย"),
    ("Togo", "Togo, Togo, Togo"),
    ("Tonga", "Tonga"),
    ("Trinidad and Tobago", "Trinidad and Tobago"),
    ("Tunisia", "Tunes, تونس"),
    ("Turkey", "Türkiye"),
    ("Turkmenistan", "Türkmenistan"),
    ("Tuvalu", "Tuvalu"),
    ("Uganda", "Uganda"),
    ("Ukraine", "Ukraїna Україна"),
    ("United Arab Emirates", "Al-’Imārat Al-‘Arabiyyah Al-Muttaḥidah الإمارات العربيّة المتّحدة"),
    ("United Kingdom", "United Kingdom, Y Deyrnas Unedig, Rìoghachd Aonaichte, Ríocht Aontaithe"),
    ("United States", "United States, Estados Unidos"),
    ("Uruguay", "Uruguay"),
    ("Uzbekistan", "O‘zbekiston Ўзбекистон"),
    ("Vanuatu", "Vanuatu"),
    ("Vatican City", "Città del Vaticano, Civitas Vaticana"),
    ("Venezuela", "Venezuela"),
    ("Vietnam", "Việt Nam"),
    ("Yemen", "Al-Yaman اليمن"),
    ("Zambia", "Zambia"),
    ("Zimbabwe", "Zimbabwe")
]

userNationalityChoices = userCountryOfAsylumChoices

# For generating countries choices from the CSV file
""" print(os.getcwd())
with open('./EndUserManagement/models/countries.csv', 'r') as read_obj:
    # pass the file object to reader() to get the reader object
    csv_reader = reader(read_obj)
    # Iterate over each row in the csv using reader object
    for row in csv_reader:
        # row variable is a list that represents a row in csv
        # print(row)
        print(f'("{row[1]}", "{row[3]}"),') """
